// Complete NON-MINISTERIAL DEPARTMENTS (24 from gov.uk)
'cma': {
  id: 'cma',
  name: 'Competition and Markets Authority',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Promotes competition and tackles anti-competitive behavior benefiting consumers',
  infoUrl: 'https://www.gov.uk/government/organisations/competition-and-markets-authority',
  parentIds: ['dbt'],
  childIds: [],
},
'cps': {
  id: 'cps',
  name: 'Crown Prosecution Service',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Prosecutes criminal cases on behalf of the state',
  infoUrl: 'https://www.gov.uk/government/organisations/crown-prosecution-service',
  parentIds: ['ago'],
  childIds: [],
},
'fsa': {
  id: 'fsa',
  name: 'Food Standards Agency',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Protects public health from food-borne risks',
  infoUrl: 'https://www.gov.uk/government/organisations/food-standards-agency',
  parentIds: ['dhsc'],
  childIds: [],
},
'forestry-commission': {
  id: 'forestry-commission',
  name: 'Forestry Commission',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Manages and protects forests in England',
  infoUrl: 'https://www.gov.uk/government/organisations/forestry-commission',
  parentIds: ['defra'],
  childIds: [],
},
'gad': {
  id: 'gad',
  name: 'Government Actuary\'s Department',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Provides actuarial advice and analysis to government departments',
  infoUrl: 'https://www.gov.uk/government/organisations/government-actuarys-department',
  parentIds: ['treasury'],
  childIds: [],
},
'gld': {
  id: 'gld',
  name: 'Government Legal Department',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Provides legal advice and services to government departments',
  infoUrl: 'https://www.gov.uk/government/organisations/government-legal-department',
  parentIds: ['ago'],
  childIds: [],
},
'hmland': {
  id: 'hmland',
  name: 'HM Land Registry',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Maintains the register of land and property in England and Wales',
  infoUrl: 'https://www.gov.uk/government/organisations/land-registry',
  parentIds: ['dluhc'],
  childIds: [],
},
'hmcpsi': {
  id: 'hmcpsi',
  name: 'HM Crown Prosecution Service Inspectorate',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Inspects the Crown Prosecution Service and maintains standards',
  infoUrl: 'https://www.gov.uk/government/organisations/hm-crown-prosecution-service-inspectorate',
  parentIds: ['ago'],
  childIds: [],
},
'hmrc': {
  id: 'hmrc',
  name: 'HM Revenue and Customs',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Administers the tax and revenue system',
  infoUrl: 'https://www.gov.uk/government/organisations/hm-revenue-customs',
  parentIds: ['treasury'],
  childIds: [],
},
'nca-non-min': {
  id: 'nca-non-min',
  name: 'National Crime Agency',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Leads the UK\'s response to serious and organized crime',
  infoUrl: 'https://www.gov.uk/government/organisations/national-crime-agency',
  parentIds: ['home-office'],
  childIds: [],
},
'nsi': {
  id: 'nsi',
  name: 'National Savings and Investments',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Manages savings and investment products for the public',
  infoUrl: 'https://www.gov.uk/government/organisations/national-savings-and-investments',
  parentIds: ['treasury'],
  childIds: [],
},
'ofsted': {
  id: 'ofsted',
  name: 'Ofsted',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Inspects education and skills providers',
  infoUrl: 'https://www.gov.uk/government/organisations/ofsted',
  parentIds: ['dfe'],
  childIds: [],
},
'ofqual': {
  id: 'ofqual',
  name: 'Office of Qualifications and Examinations Regulation',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Regulates qualifications, exams and assessment services',
  infoUrl: 'https://www.gov.uk/government/organisations/ofqual',
  parentIds: ['dfe'],
  childIds: [],
},
'orr': {
  id: 'orr',
  name: 'Office of Rail and Road',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Regulates rail and roads in Great Britain',
  infoUrl: 'https://www.gov.uk/government/organisations/office-of-rail-and-road',
  parentIds: ['dft'],
  childIds: [],
},
'ofgem': {
  id: 'ofgem',
  name: 'Ofgem',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Regulates electricity and gas markets',
  infoUrl: 'https://www.gov.uk/government/organisations/ofgem',
  parentIds: ['desnz'],
  childIds: [],
},
'sfo': {
  id: 'sfo',
  name: 'Serious Fraud Office',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Investigates and prosecutes serious or complex fraud',
  infoUrl: 'https://www.gov.uk/government/organisations/serious-fraud-office',
  parentIds: ['ago'],
  childIds: [],
},
'charity-comm': {
  id: 'charity-comm',
  name: 'The Charity Commission',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Regulates charities in England and Wales',
  infoUrl: 'https://www.gov.uk/government/organisations/charity-commission',
  parentIds: ['dcms'],
  childIds: [],
},
'nats': {
  id: 'nats',
  name: 'The National Archives',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Preserves government records and historical documents',
  infoUrl: 'https://www.gov.uk/government/organisations/the-national-archives',
  parentIds: ['dcms'],
  childIds: [],
},
'ofwat': {
  id: 'ofwat',
  name: 'The Water Services Regulation Authority',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Regulates water and sewerage services in England and Wales',
  infoUrl: 'https://www.gov.uk/government/organisations/the-water-services-regulation-authority',
  parentIds: ['defra'],
  childIds: [],
},
'uksa': {
  id: 'uksa',
  name: 'UK Statistics Authority',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Oversees production of official statistics',
  infoUrl: 'https://www.gov.uk/government/organisations/uk-statistics-authority',
  parentIds: ['co'],
  childIds: [],
},
'nic': {
  id: 'nic',
  name: 'National Infrastructure Commission',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Provides independent analysis and recommendations on long-term infrastructure needs',
  infoUrl: 'https://www.gov.uk/government/organisations/national-infrastructure-commission',
  parentIds: ['treasury'],
  childIds: [],
},
'ipo': {
  id: 'ipo',
  name: 'Intellectual Property Office',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Manages intellectual property rights including patents and trademarks',
  infoUrl: 'https://www.gov.uk/government/organisations/intellectual-property-office',
  parentIds: ['dsit'],
  childIds: [],
},
'met-office': {
  id: 'met-office',
  name: 'Met Office',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Provides weather forecasting and meteorological services',
  infoUrl: 'https://www.gov.uk/government/organisations/met-office',
  parentIds: ['dsit'],
  childIds: [],
},
'uk-health-security': {
  id: 'uk-health-security',
  name: 'UK Health Security Agency',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Protects UK residents from infectious disease threats and public health emergencies',
  infoUrl: 'https://www.gov.uk/government/organisations/uk-health-security-agency',
  parentIds: ['dhsc'],
  childIds: [],
},
'mhra': {
  id: 'mhra',
  name: 'Medicines and Healthcare Products Regulatory Agency',
  category: 'department',
  subtype: 'non-ministerial',
  description: 'Regulates medicines, medical devices and blood products for safety and efficacy',
  infoUrl: 'https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency',
  parentIds: ['dhsc'],
  childIds: [],
},

// EXECUTIVE AGENCIES (37 from gov.uk)
'active-travel-england': {
  id: 'active-travel-england',
  name: 'Active Travel England',
  category: 'department',
  subtype: 'agency',
  description: 'Promotes walking and cycling through infrastructure investment',
  infoUrl: 'https://www.gov.uk/government/organisations/active-travel-england',
  parentIds: ['dft'],
  childIds: [],
},
'apha': {
  id: 'apha',
  name: 'Animal and Plant Health Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Protects animal and plant health, manages disease control',
  infoUrl: 'https://www.gov.uk/government/organisations/animal-and-plant-health-agency',
  parentIds: ['defra'],
  childIds: [],
},
'building-digital-uk': {
  id: 'building-digital-uk',
  name: 'Building Digital UK',
  category: 'department',
  subtype: 'agency',
  description: 'Delivers digital infrastructure programmes across the UK',
  infoUrl: 'https://www.gov.uk/government/organisations/building-digital-uk',
  parentIds: ['dsit'],
  childIds: [],
},
'cefas': {
  id: 'cefas',
  name: 'Centre for Environment, Fisheries and Aquaculture Science',
  category: 'department',
  subtype: 'agency',
  description: 'Provides research and scientific advice on fisheries and marine environment',
  infoUrl: 'https://www.gov.uk/government/organisations/centre-for-environment-fisheries-and-aquaculture-science',
  parentIds: ['defra'],
  childIds: [],
},
'companies-house': {
  id: 'companies-house',
  name: 'Companies House',
  category: 'department',
  subtype: 'agency',
  description: 'Registers and manages company information',
  infoUrl: 'https://www.gov.uk/government/organisations/companies-house',
  parentIds: ['dbt'],
  childIds: [],
},
'cica': {
  id: 'cica',
  name: 'Criminal Injuries Compensation Authority',
  category: 'department',
  subtype: 'agency',
  description: 'Awards compensation to victims of violent crime',
  infoUrl: 'https://www.gov.uk/government/organisations/criminal-injuries-compensation-authority',
  parentIds: ['moj'],
  childIds: [],
},
'ccs': {
  id: 'ccs',
  name: 'Crown Commercial Service',
  category: 'department',
  subtype: 'agency',
  description: 'Manages government procurement and commercial strategy',
  infoUrl: 'https://www.gov.uk/government/organisations/crown-commercial-service',
  parentIds: ['co'],
  childIds: [],
},
'des': {
  id: 'des',
  name: 'Defence Equipment and Support',
  category: 'department',
  subtype: 'agency',
  description: 'Manages defence procurement and logistical support',
  infoUrl: 'https://www.gov.uk/government/organisations/defence-equipment-and-support',
  parentIds: ['mod'],
  childIds: [],
},
'dstl': {
  id: 'dstl',
  name: 'Defence Science and Technology Laboratory',
  category: 'department',
  subtype: 'agency',
  description: 'Conducts scientific research to support UK defence and security',
  infoUrl: 'https://www.gov.uk/government/organisations/defence-science-and-technology-laboratory',
  parentIds: ['mod'],
  childIds: [],
},
'dvla': {
  id: 'dvla',
  name: 'Driver and Vehicle Licensing Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Manages vehicle registration, licensing, and driving licenses for Great Britain',
  infoUrl: 'https://www.gov.uk/government/organisations/driver-and-vehicle-licensing-agency',
  parentIds: ['dft'],
  childIds: [],
},
'dvsa': {
  id: 'dvsa',
  name: 'Driver and Vehicle Standards Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Regulates heavy vehicles and operates MOT testing and vehicle operator licensing',
  infoUrl: 'https://www.gov.uk/government/organisations/driver-and-vehicle-standards-agency',
  parentIds: ['dft'],
  childIds: [],
},
'esfa': {
  id: 'esfa',
  name: 'Education and Skills Funding Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Manages funding for education institutions and training providers',
  infoUrl: 'https://www.gov.uk/government/organisations/education-and-skills-funding-agency',
  parentIds: ['dfe'],
  childIds: [],
},
'giaa': {
  id: 'giaa',
  name: 'Government Internal Audit Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Provides internal audit services to government departments',
  infoUrl: 'https://www.gov.uk/government/organisations/government-internal-audit-agency',
  parentIds: ['treasury'],
  childIds: [],
},
'gpa': {
  id: 'gpa',
  name: 'Government Property Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Manages government property and estate strategy',
  infoUrl: 'https://www.gov.uk/government/organisations/government-property-agency',
  parentIds: ['co'],
  childIds: [],
},
'hmcts': {
  id: 'hmcts',
  name: 'HM Courts and Tribunals Service',
  category: 'department',
  subtype: 'agency',
  description: 'Runs civil and criminal courts across England and Wales',
  infoUrl: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service',
  parentIds: ['moj'],
  childIds: [],
},
'hmpps': {
  id: 'hmpps',
  name: 'HM Prison and Probation Service',
  category: 'department',
  subtype: 'agency',
  description: 'Manages prisons and probation services',
  infoUrl: 'https://www.gov.uk/government/organisations/hm-prison-and-probation-service',
  parentIds: ['moj'],
  childIds: [],
},
'insolvency-service': {
  id: 'insolvency-service',
  name: 'Insolvency Service',
  category: 'department',
  subtype: 'agency',
  description: 'Administers insolvency law and personal debt solutions',
  infoUrl: 'https://www.gov.uk/government/organisations/the-insolvency-service',
  parentIds: ['dbt'],
  childIds: [],
},
'legal-aid': {
  id: 'legal-aid',
  name: 'Legal Aid Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Provides legal aid services to eligible individuals',
  infoUrl: 'https://www.gov.uk/government/organisations/legal-aid-agency',
  parentIds: ['moj'],
  childIds: [],
},
'maritime-coastguard': {
  id: 'maritime-coastguard',
  name: 'Maritime and Coastguard Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Operates search and rescue services and enforces maritime safety regulations',
  infoUrl: 'https://www.gov.uk/government/organisations/maritime-and-coastguard-agency',
  parentIds: ['dft'],
  childIds: [],
},
'opg': {
  id: 'opg',
  name: 'Office of the Public Guardian',
  category: 'department',
  subtype: 'agency',
  description: 'Protects the property and affairs of vulnerable people',
  infoUrl: 'https://www.gov.uk/government/organisations/office-of-the-public-guardian',
  parentIds: ['moj'],
  childIds: [],
},
'planning-inspectorate': {
  id: 'planning-inspectorate',
  name: 'Planning Inspectorate',
  category: 'department',
  subtype: 'agency',
  description: 'Conducts planning appeals and infrastructure planning inquiries',
  infoUrl: 'https://www.gov.uk/government/organisations/planning-inspectorate',
  parentIds: ['dluhc'],
  childIds: [],
},
'qeiicc': {
  id: 'qeiicc',
  name: 'Queen Elizabeth II Conference Centre',
  category: 'department',
  subtype: 'agency',
  description: 'Provides conference and event facilities in Westminster',
  infoUrl: 'https://www.gov.uk/government/organisations/queen-elizabeth-ii-conference-centre',
  parentIds: ['dluhc'],
  childIds: [],
},
'rpa': {
  id: 'rpa',
  name: 'Rural Payments Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Administers grants and subsidies for farmers and rural land managers',
  infoUrl: 'https://www.gov.uk/government/organisations/rural-payments-agency',
  parentIds: ['defra'],
  childIds: [],
},
'sta': {
  id: 'sta',
  name: 'Standards and Testing Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Develops and manages national curriculum assessments and qualifications',
  infoUrl: 'https://www.gov.uk/government/organisations/standards-and-testing-agency',
  parentIds: ['dfe'],
  childIds: [],
},
'sda': {
  id: 'sda',
  name: 'Submarine Delivery Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Delivers the UK\'s future nuclear-powered submarines',
  infoUrl: 'https://www.gov.uk/government/organisations/submarine-delivery-agency',
  parentIds: ['mod'],
  childIds: [],
},
'tra': {
  id: 'tra',
  name: 'Teaching Regulation Authority',
  category: 'department',
  subtype: 'agency',
  description: 'Maintains standards of conduct for the teaching profession',
  infoUrl: 'https://www.gov.uk/government/organisations/teaching-regulation-authority',
  parentIds: ['dfe'],
  childIds: [],
},
'ukdmo': {
  id: 'ukdmo',
  name: 'UK Debt Management Office',
  category: 'department',
  subtype: 'agency',
  description: 'Manages government borrowing and the national debt',
  infoUrl: 'https://www.gov.uk/government/organisations/uk-debt-management-office',
  parentIds: ['treasury'],
  childIds: [],
},
'uk-hydrographic': {
  id: 'uk-hydrographic',
  name: 'UK Hydrographic Office',
  category: 'department',
  subtype: 'agency',
  description: 'Produces and supplies hydrographic data for maritime navigation',
  infoUrl: 'https://www.gov.uk/government/organisations/uk-hydrographic-office',
  parentIds: ['mod'],
  childIds: [],
},
'uk-space-agency': {
  id: 'uk-space-agency',
  name: 'UK Space Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Leads the UK\'s space sector development and investment',
  infoUrl: 'https://www.gov.uk/government/organisations/uk-space-agency',
  parentIds: ['dsit'],
  childIds: [],
},
'voa': {
  id: 'voa',
  name: 'Valuation Office Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Values property for tax purposes and manages the rating system',
  infoUrl: 'https://www.gov.uk/government/organisations/valuation-office-agency',
  parentIds: ['hmrc'],
  childIds: [],
},
'vca': {
  id: 'vca',
  name: 'Vehicle Certification Agency',
  category: 'department',
  subtype: 'agency',
  description: 'Certifies vehicles for environmental and safety standards',
  infoUrl: 'https://www.gov.uk/government/organisations/vehicle-certification-agency',
  parentIds: ['dft'],
  childIds: [],
},
'vmd': {
  id: 'vmd',
  name: 'Veterinary Medicines Directorate',
  category: 'department',
  subtype: 'agency',
  description: 'Authorises and regulates veterinary medicines',
  infoUrl: 'https://www.gov.uk/government/organisations/veterinary-medicines-directorate',
  parentIds: ['defra'],
  childIds: [],
},
'wilton-park': {
  id: 'wilton-park',
  name: 'Wilton Park',
  category: 'department',
  subtype: 'agency',
  description: 'Delivers policy-relevant conferences and educational programmes',
  infoUrl: 'https://www.gov.uk/government/organisations/wilton-park',
  parentIds: ['fcdo'],
  childIds: [],
},
