import { readFileSync, writeFileSync } from 'fs'

const filePath = new URL('../src/data/elements.ts', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')

// ── Tag assignments: id -> string[] ──────────────────────────────────────────
// Tags: type tags (what kind of body) + sector tags (what it does)
const tagMap = {

  // ── HIGH PROFILE GROUPS (all new entries + building-digital-uk already existed) ──
  'ai-security-institute':           ['high-profile-group', 'sector-security', 'sector-digital', 'sector-science'],
  'govt-chemist':                    ['high-profile-group', 'sector-food-farming', 'sector-science'],
  'govt-digital-service':            ['high-profile-group', 'sector-digital'],
  'govt-office-tech-transfer':       ['high-profile-group', 'sector-science', 'sector-business'],
  'office-digital-identities':       ['high-profile-group', 'sector-digital'],
  'regulatory-innovation-office':    ['high-profile-group', 'sector-digital', 'sector-science'],
  'research-collab-advice':          ['high-profile-group', 'sector-science'],
  'govt-science-engineering':        ['high-profile-group', 'profession', 'sector-science'],
  'cabinet-office-board':            ['high-profile-group'],
  'civil-service-fast-stream':       ['high-profile-group', 'profession'],
  'civil-service-group':             ['high-profile-group'],
  'disability-unit':                 ['high-profile-group', 'sector-welfare'],
  'govt-analysis-function':          ['high-profile-group', 'profession'],
  'govt-commercial-function':        ['high-profile-group', 'profession', 'sector-business'],
  'govt-communication-service':      ['high-profile-group', 'profession'],
  'govt-data-quality-hub':           ['high-profile-group', 'profession', 'sector-digital'],
  'govt-finance-function':           ['high-profile-group', 'profession', 'sector-finance'],
  'govt-legal-profession':           ['high-profile-group', 'profession', 'sector-legal'],
  'govt-occupational-psych':         ['high-profile-group', 'profession'],
  'govt-operational-research':       ['high-profile-group', 'profession'],
  'govt-people-group':               ['high-profile-group', 'profession'],
  'govt-project-delivery':           ['high-profile-group', 'profession'],
  'govt-recruitment-service':        ['high-profile-group'],
  'govt-security-profession':        ['high-profile-group', 'profession', 'sector-security'],
  'govt-skills':                     ['high-profile-group', 'profession'],
  'intelligence-analysis':           ['high-profile-group', 'sector-security', 'sector-international'],
  'leadership-college-govt':         ['high-profile-group'],
  'modernisation-reform':            ['high-profile-group'],
  'national-security-intelligence':  ['high-profile-group', 'sector-security'],
  'national-cyber-security':         ['high-profile-group', 'sector-cyber', 'sector-security'],
  'office-parliamentary-counsel':    ['high-profile-group', 'sector-legal'],
  'open-public-services':            ['high-profile-group'],
  'public-sector-fraud-authority':   ['high-profile-group', 'sector-finance'],
  'race-equality-unit':              ['high-profile-group'],
  'uk-integrated-security-fund':     ['high-profile-group', 'sector-security', 'sector-international'],
  'uk-resilience-academy':           ['high-profile-group'],
  'uk-security-vetting':             ['high-profile-group', 'sector-security'],
  'women-equalities-unit':           ['high-profile-group'],
  'govt-property-function':          ['high-profile-group', 'profession'],
  'govt-partnerships-intl':          ['high-profile-group', 'sector-international'],
  'govt-geography-profession':       ['high-profile-group', 'profession'],
  'govt-knowledge-mgmt':             ['high-profile-group', 'profession'],
  'operational-delivery-profession': ['high-profile-group', 'profession'],
  'policy-profession':               ['high-profile-group', 'profession'],
  'govt-social-research':            ['high-profile-group', 'profession'],
  'accel-capability-env':            ['high-profile-group', 'sector-digital', 'sector-security'],
  'border-force':                    ['high-profile-group', 'police', 'sector-immigration'],
  'border-security-command':         ['high-profile-group', 'sector-security', 'sector-immigration'],
  'hm-passport-office':              ['high-profile-group', 'sector-immigration'],
  'immigration-enforcement':         ['high-profile-group', 'police', 'sector-immigration'],
  'national-protective-security':    ['high-profile-group', 'sector-security'],
  'office-independent-examiner':     ['high-profile-group'],
  'cyber-specialist-ops':            ['high-profile-group', 'armed-forces', 'sector-cyber', 'sector-defence'],
  'defence-academy':                 ['high-profile-group', 'armed-forces', 'sector-defence'],
  'defence-infrastructure-org':      ['high-profile-group', 'armed-forces', 'sector-defence'],
  'defence-nuclear-org':             ['high-profile-group', 'armed-forces', 'sector-defence', 'sector-nuclear'],
  'defence-safety-authority':        ['high-profile-group', 'regulator', 'armed-forces', 'sector-defence'],
  'defence-sixth-form':              ['high-profile-group', 'armed-forces', 'sector-defence', 'sector-education'],
  'kings-harbour-master':            ['high-profile-group', 'armed-forces', 'sector-defence'],
  'military-aviation-authority':     ['high-profile-group', 'regulator', 'armed-forces', 'sector-defence', 'sector-transport'],
  'national-cyber-force':            ['high-profile-group', 'armed-forces', 'sector-cyber', 'sector-defence'],
  'national-space-ops-centre':       ['high-profile-group', 'armed-forces', 'sector-defence', 'sector-science'],
  'office-veterans-affairs':         ['high-profile-group', 'sector-veterans', 'sector-defence'],
  'uk-defence-innovation':           ['high-profile-group', 'armed-forces', 'sector-defence', 'sector-science'],
  'uk-reserve-forces-assoc':         ['high-profile-group', 'armed-forces', 'sector-defence', 'sector-veterans'],
  'veterans-uk':                     ['high-profile-group', 'sector-veterans', 'sector-defence'],
  'jhub-defence-innovation':         ['high-profile-group', 'armed-forces', 'sector-cyber', 'sector-defence'],
  'gov-facility-services':           ['high-profile-group', 'sector-justice'],
  'office-zero-emission-vehicles':   ['high-profile-group', 'sector-transport', 'sector-environment'],
  'flood-coastal-erosion-rnd':       ['high-profile-group', 'sector-environment'],
  'govt-veterinary-services':        ['high-profile-group', 'sector-food-farming'],
  'offshore-petroleum-regulator':    ['high-profile-group', 'regulator', 'sector-energy', 'sector-environment'],
  'further-education-commissioner':  ['high-profile-group', 'sector-education'],
  'regional-dfe-directors':          ['high-profile-group', 'sector-education'],
  'uk-council-internet-safety':      ['high-profile-group', 'sector-digital', 'sector-education'],
  'office-health-improvement':       ['high-profile-group', 'sector-health'],
  'office-life-sciences':            ['high-profile-group', 'sector-health', 'sector-science', 'sector-business'],
  'uk-national-screening':           ['high-profile-group', 'adviser', 'sector-health'],
  'medical-profession':              ['high-profile-group', 'profession', 'sector-health'],
  'centre-connected-vehicles':       ['high-profile-group', 'sector-transport', 'sector-digital'],
  'employment-agency-standards':     ['high-profile-group', 'regulator', 'sector-business'],
  'export-control-joint-unit':       ['high-profile-group', 'regulator', 'sector-business', 'sector-international', 'sector-defence'],
  'office-investment':               ['high-profile-group', 'sector-business', 'sector-finance'],
  'office-investment-fs':            ['high-profile-group', 'sector-finance', 'sector-business'],
  'office-product-safety':           ['high-profile-group', 'regulator', 'sector-business'],
  'office-responsible-business':     ['high-profile-group', 'sector-business', 'sector-international'],
  'office-pay-review-bodies':        ['high-profile-group', 'review-body'],
  'office-trade-sanctions':          ['high-profile-group', 'regulator', 'sector-business', 'sector-international'],
  'uk-defence-security-exports':     ['high-profile-group', 'sector-business', 'sector-defence', 'sector-international'],
  'uk-national-contact-point':       ['high-profile-group', 'sector-business', 'sector-international'],
  'preventing-sexual-violence':      ['high-profile-group', 'sector-international'],
  'uk-national-auth-counter-eaves':  ['high-profile-group', 'sector-security'],
  'bona-vacantia':                   ['high-profile-group', 'sector-legal', 'sector-finance'],
  'office-financial-sanctions':      ['high-profile-group', 'sector-finance', 'sector-international'],
  'govt-corporate-finance':          ['high-profile-group', 'profession', 'sector-finance'],
  'govt-economic-service':           ['high-profile-group', 'profession', 'sector-finance'],
  'windrush-commemoration':          ['high-profile-group', 'sector-culture'],
  'govt-planning-profession':        ['high-profile-group', 'profession', 'sector-planning'],
  'district-valuer-services':        ['high-profile-group', 'sector-housing', 'sector-finance'],
  'centre-climate-health-security':  ['high-profile-group', 'sector-health', 'sector-environment'],
  'health-equity-initiative':        ['high-profile-group', 'sector-health'],
  'ahrc':                            ['high-profile-group', 'research-council', 'sector-culture', 'sector-science'],
  'bbsrc':                           ['high-profile-group', 'research-council', 'sector-science', 'sector-food-farming', 'sector-health'],
  'esrc':                            ['high-profile-group', 'research-council', 'sector-science'],
  'epsrc':                           ['high-profile-group', 'research-council', 'sector-science'],
  'mrc':                             ['high-profile-group', 'research-council', 'sector-science', 'sector-health'],
  'nerc':                            ['high-profile-group', 'research-council', 'sector-science', 'sector-environment'],
  'stfc':                            ['high-profile-group', 'research-council', 'sector-science'],
  'innovate-uk':                     ['high-profile-group', 'research-council', 'sector-science', 'sector-business'],
  'research-england':                ['high-profile-group', 'research-council', 'sector-science', 'sector-education'],
  'office-internal-market':          ['high-profile-group', 'regulator', 'sector-business'],
  'subsidy-advice-unit':             ['high-profile-group', 'adviser', 'sector-business', 'sector-finance'],
  'hm-prison-service':               ['high-profile-group', 'sector-justice'],
  'probation-service':               ['high-profile-group', 'sector-justice'],
  'youth-custody-service':           ['high-profile-group', 'sector-justice', 'sector-education'],
  'hm-nautical-almanac':             ['high-profile-group', 'trading-fund', 'sector-transport'],
  'fleet-air-arm-museum':            ['high-profile-group', 'museum-gallery', 'sector-culture', 'sector-defence'],
  'royal-marines-museum':            ['high-profile-group', 'museum-gallery', 'sector-culture', 'sector-defence'],
  'royal-navy-submarine-museum':     ['high-profile-group', 'museum-gallery', 'sector-culture', 'sector-defence'],
  'national-guardians-office':       ['high-profile-group', 'sector-health'],
  'uk-industrial-fusion':            ['high-profile-group', 'sector-energy', 'sector-nuclear', 'sector-science'],
  'british-cattle-movement':         ['high-profile-group', 'sector-food-farming'],
  'civil-nuclear-constabulary':      ['high-profile-group', 'police', 'sector-nuclear', 'sector-security'],
  'govt-planning-inspectors':        ['high-profile-group', 'inspector', 'sector-planning'],
  'internal-audit-profession':       ['high-profile-group', 'profession', 'sector-finance'],
  'govt-statistical-service':        ['high-profile-group', 'profession', 'sector-science'],
  'govt-tax-profession':             ['high-profile-group', 'profession', 'sector-finance'],
  'building-digital-uk':             ['high-profile-group', 'sector-digital'],

  // ── Existing elements: type tags ──────────────────────────────────────────

  // Ministerial departments — sector tags
  'ago':            ['sector-legal'],
  'co':             [],
  'dbt':            ['sector-business', 'sector-finance'],
  'dcms':           ['sector-culture', 'sector-media', 'sector-digital'],
  'defra':          ['sector-environment', 'sector-food-farming'],
  'desnz':          ['sector-energy', 'sector-environment'],
  'dfe':            ['sector-education'],
  'dft':            ['sector-transport'],
  'dhsc':           ['sector-health'],
  'dluhc':          ['sector-housing', 'sector-planning', 'sector-construction'],
  'dsit':           ['sector-digital', 'sector-science'],
  'dwp':            ['sector-welfare'],
  'fcdo':           ['sector-international'],
  'home-office':    ['sector-immigration', 'sector-security'],
  'mod':            ['sector-defence'],
  'moj':            ['sector-justice', 'sector-legal'],
  'ni-office':      [],
  'pm-office':      [],
  'scotland-office': [],
  'treasury':       ['sector-finance'],
  'wales-office':   [],
  'ukef':           ['sector-business', 'sector-finance', 'sector-international'],

  // Non-ministerial departments
  'charity-comm':    ['regulator', 'sector-charities'],
  'cma':             ['regulator', 'sector-business', 'sector-finance'],
  'cps':             ['prosecution', 'sector-legal', 'sector-justice'],
  'forestry-commission': ['regulator', 'sector-environment'],
  'fsa':             ['regulator', 'sector-food-farming', 'sector-health'],
  'gad':             ['sector-finance'],
  'gld':             ['sector-legal'],
  'hmcpsi':          ['inspector', 'sector-legal', 'sector-justice'],
  'hmland':          ['sector-housing', 'sector-legal'],
  'hmrc':            ['regulator', 'sector-finance'],
  'nats':            ['trading-fund', 'sector-transport'],
  'nca-non-min':     ['police', 'sector-security', 'sector-justice'],
  'nsi':             ['trading-fund', 'sector-finance'],
  'ofgem':           ['regulator', 'sector-energy'],
  'ofqual':          ['regulator', 'sector-education'],
  'ofsted':          ['inspector', 'sector-education'],
  'ofwat':           ['regulator', 'sector-environment'],
  'orr':             ['regulator', 'sector-transport'],
  'sfo':             ['prosecution', 'sector-legal', 'sector-justice', 'sector-finance'],
  'supreme-court':   ['sector-legal', 'sector-justice'],
  'uksa':            ['regulator', 'sector-science'],
  'ons':             ['sector-science', 'sector-finance'],
  'giaa':            ['sector-finance'],
  'voa':             ['sector-housing', 'sector-finance'],
  'ukdmo':           ['sector-finance'],
  'planning-inspectorate': ['inspector', 'sector-planning'],

  // Executive agencies
  'active-travel-england': ['sector-transport', 'sector-environment'],
  'apha':            ['regulator', 'sector-food-farming', 'sector-environment'],
  'ccs':             ['sector-business', 'sector-finance'],
  'cefas':           ['sector-environment', 'sector-food-farming', 'sector-science'],
  'cica':            ['sector-justice'],
  'companies-house': ['regulator', 'sector-business'],
  'des':             ['armed-forces', 'sector-defence'],
  'dstl':            ['armed-forces', 'sector-defence', 'sector-science'],
  'dvla':            ['sector-transport'],
  'dvsa':            ['regulator', 'sector-transport'],
  'esfa':            ['sector-education', 'sector-finance'],
  'forest-research': ['sector-environment', 'sector-science'],
  'forestry-england': ['sector-environment'],
  'gpa':             ['sector-housing'],
  'hmcts':           ['sector-justice', 'sector-legal'],
  'hmpps':           ['sector-justice'],
  'insolvency-service': ['regulator', 'sector-business', 'sector-finance'],
  'ipo':             ['regulator', 'sector-business', 'sector-digital'],
  'legal-aid':       ['sector-legal', 'sector-justice'],
  'legal-services-ni': ['sector-legal'],
  'maritime-coastguard': ['regulator', 'sector-transport'],
  'met-office':      ['sector-environment', 'sector-science'],
  'mhra':            ['regulator', 'sector-health'],
  'ni-courts-tribunals': ['tribunal', 'sector-legal'],
  'ni-prison-service': ['sector-justice'],
  'ni-statistics':   ['sector-science'],
  'opg':             ['sector-legal', 'sector-health'],
  'qeiicc':          ['sector-culture'],
  'rpa':             ['sector-food-farming', 'sector-finance'],
  'sda':             ['armed-forces', 'sector-defence', 'sector-nuclear'],
  'skills-england':  ['sector-education', 'sector-business'],
  'sta':             ['sector-education'],
  'tra':             ['regulator', 'sector-education'],
  'uk-health-security': ['sector-health', 'sector-security'],
  'uk-hydrographic': ['trading-fund', 'sector-transport', 'sector-defence'],
  'uk-space-agency': ['sector-science', 'sector-transport'],
  'ukdmo':           ['trading-fund', 'sector-finance'],
  'vca':             ['regulator', 'sector-transport'],
  'vmd':             ['regulator', 'sector-food-farming'],
  'voa':             ['sector-housing', 'sector-finance'],
  'wilton-park':     ['sector-international'],
  'youth-justice-ni': ['sector-justice', 'sector-education'],

  // Executive NDPBs
  'acas':            ['adviser', 'sector-business'],
  'afcft':           ['adviser', 'sector-veterans'],
  'ahdb':            ['adviser', 'sector-food-farming'],
  'aria':            ['sector-science', 'sector-digital'],
  'arts-council-england': ['sector-culture'],
  'awe':             ['armed-forces', 'sector-defence', 'sector-nuclear'],
  'bank-of-england': ['regulator', 'sector-finance'],
  'bfi':             ['sector-culture', 'sector-media'],
  'british-council': ['sector-international', 'sector-culture', 'sector-education'],
  'british-hallmarking': ['regulator', 'sector-business'],
  'british-library': ['museum-gallery', 'sector-culture', 'sector-education'],
  'british-museum':  ['museum-gallery', 'sector-culture'],
  'btpa':            ['police', 'sector-transport'],
  'building-safety-reg': ['regulator', 'sector-housing', 'sector-construction'],
  'cafcass':         ['sector-justice', 'sector-education'],
  'ccc':             ['adviser', 'sector-environment', 'sector-energy'],
  'ccrc':            ['sector-justice', 'sector-legal'],
  'citb':            ['sector-construction', 'sector-education'],
  'civil-nuclear-police': ['police', 'sector-nuclear', 'sector-security'],
  'civil-service-commission': ['regulator'],
  'competition-service': ['tribunal', 'sector-business'],
  'consumer-council-water': ['adviser', 'sector-environment'],
  'corporate-officers-commons': ['sector-legal'],
  'corporate-officers-lords': ['sector-legal'],
  'cqc':             ['regulator', 'inspector', 'sector-health'],
  'csc-uk':          ['sector-international'],
  'dbs':             ['regulator', 'sector-justice', 'sector-education'],
  'east-west-railway': ['sector-transport'],
  'ebbsfleet-dev':   ['development-corp', 'sector-housing', 'sector-planning'],
  'ecitb':           ['sector-construction', 'sector-education'],
  'ehrc':            ['regulator', 'adviser'],
  'environment-agency': ['regulator', 'sector-environment'],
  'frc':             ['regulator', 'sector-finance', 'sector-business'],
  'gambling-commission': ['regulator', 'sector-gambling'],
  'gb-china-centre': ['sector-international'],
  'gbe-nuclear':     ['sector-nuclear', 'sector-energy'],
  'glaa':            ['regulator', 'sector-business', 'sector-immigration'],
  'hblb':            ['sector-culture'],
  'hfea':            ['regulator', 'sector-health', 'sector-science'],
  'historic-england': ['regulator', 'adviser', 'sector-culture', 'sector-planning'],
  'homes-england':   ['development-corp', 'sector-housing'],
  'horniman-museum': ['museum-gallery', 'sector-culture'],
  'housing-ombudsman': ['ombudsman', 'sector-housing'],
  'hra':             ['regulator', 'sector-health', 'sector-science'],
  'hs2':             ['development-corp', 'sector-transport'],
  'hsa':             ['regulator', 'sector-environment', 'sector-nuclear'],
  'hsc-bso-ni':      ['sector-health'],
  'hssib':           ['inspector', 'sector-health'],
  'hta':             ['regulator', 'sector-health', 'sector-science'],
  'ico':             ['regulator', 'sector-digital'],
  'icrir':           ['sector-justice'],
  'ifca':            ['regulator', 'sector-environment', 'sector-food-farming'],
  'ifr':             ['sector-culture'],
  'ima':             ['regulator', 'sector-immigration'],
  'immigration-advice-auth': ['regulator', 'sector-immigration', 'sector-legal'],
  'iopc':            ['inspector', 'police', 'sector-justice'],
  'iwm':             ['museum-gallery', 'sector-culture', 'sector-defence'],
  'jac':             ['sector-legal', 'sector-justice'],
  'jncc':            ['adviser', 'sector-environment'],
  'kew-gardens':     ['sector-environment', 'sector-science'],
  'lease':           ['adviser', 'sector-housing', 'sector-legal'],
  'lmc-ni':          ['sector-legal'],
  'located':         ['sector-education'],
  'lsb':             ['regulator', 'sector-legal'],
  'macc':            ['sector-international'],
  'maps':            ['adviser', 'sector-finance', 'sector-welfare'],
  'mining-rem-auth': ['sector-environment', 'sector-business'],
  'mmo':             ['regulator', 'sector-environment', 'sector-food-farming'],
  'museum-home':     ['museum-gallery', 'sector-culture', 'sector-justice'],
  'national-army-museum': ['museum-gallery', 'sector-culture', 'sector-defence'],
  'national-gallery': ['museum-gallery', 'sector-culture'],
  'national-highways': ['sector-transport'],
  'national-museums-liverpool': ['museum-gallery', 'sector-culture'],
  'natural-england': ['regulator', 'adviser', 'sector-environment'],
  'nda':             ['sector-nuclear', 'sector-energy', 'sector-environment'],
  'network-rail':    ['sector-transport'],
  'nhm':             ['museum-gallery', 'sector-culture', 'sector-science'],
  'nhmf':            ['lottery', 'sector-culture', 'sector-environment'],
  'nhs-improve':     ['regulator', 'nhs-body', 'sector-health'],
  'nhsbsa':          ['nhs-body', 'sector-health', 'sector-finance'],
  'nhsbt':           ['nhs-body', 'sector-health'],
  'nhscfa':          ['sector-health', 'sector-finance', 'sector-justice'],
  'nhsr':            ['sector-health'],
  'niccea':          ['regulator', 'sector-education'],
  'nice':            ['adviser', 'nhs-body', 'sector-health'],
  'nihe':            ['development-corp', 'sector-housing'],
  'nihrc':           ['adviser', 'sector-legal'],
  'nipb':            ['sector-justice'],
  'nlb':             ['sector-transport'],
  'nlcf':            ['lottery', 'sector-culture', 'sector-charities'],
  'nmrn':            ['museum-gallery', 'sector-culture', 'sector-defence'],
  'npg':             ['museum-gallery', 'sector-culture'],
  'nsta':            ['regulator', 'sector-energy'],
  'nwf':             ['sector-finance'],
  'oak-national-academy': ['sector-education', 'sector-digital'],
  'obr':             ['adviser', 'sector-finance'],
  'occ':             ['sector-education'],
  'oep':             ['regulator', 'inspector', 'sector-environment'],
  'ofcom':           ['regulator', 'sector-media', 'sector-digital', 'sector-communications'],
  'ofstu':           ['inspector', 'sector-education'],
  'parole-board':    ['tribunal', 'sector-justice'],
  'pra':             ['regulator', 'sector-finance'],
  'psni':            ['police', 'sector-security', 'sector-justice'],
  'raf-museum':      ['museum-gallery', 'sector-culture', 'sector-defence'],
  'reclaim-fund':    ['sector-finance', 'sector-charities'],
  'rmg':             ['museum-gallery', 'sector-culture'],
  'royal-armouries': ['museum-gallery', 'sector-culture', 'sector-defence'],
  'rsh':             ['regulator', 'sector-housing'],
  'salix':           ['sector-energy', 'sector-environment'],
  'sbc':             ['sector-business'],
  'science-museum-group': ['museum-gallery', 'sector-culture', 'sector-science'],
  'seafish':         ['adviser', 'sector-food-farming', 'sector-environment'],
  'sgsa':            ['regulator', 'sector-culture'],
  'sia':             ['regulator', 'sector-security'],
  'slc':             ['sector-education', 'sector-finance'],
  'soane-museum':    ['museum-gallery', 'sector-culture'],
  'social-work-england': ['regulator', 'sector-health'],
  'sport-england':   ['sector-culture'],
  'ssro':            ['regulator', 'sector-defence', 'sector-finance'],
  'tate':            ['museum-gallery', 'sector-culture'],
  'tra-body':        ['tribunal', 'sector-business', 'sector-international'],
  'transport-focus': ['adviser', 'sector-transport'],
  'trinity-house':   ['trading-fund', 'sector-transport'],
  'uk-sport':        ['sector-culture'],
  'ukad':            ['regulator', 'sector-culture'],
  'ukaea':           ['sector-nuclear', 'sector-energy', 'sector-science'],
  'ukib':            ['sector-finance', 'sector-business'],
  'ukri':            ['research-council', 'sector-science'],
  'vam':             ['museum-gallery', 'sector-culture'],
  'visitbritain':    ['sector-culture', 'sector-business'],
  'visitengland':    ['sector-culture', 'sector-business'],
  'vts':             ['sector-housing'],
  'wallace-collection': ['museum-gallery', 'sector-culture'],
  'wfd':             ['sector-international', 'sector-culture'],
  'yjb':             ['adviser', 'sector-justice', 'sector-education'],

  // Advisory NDPBs
  'acaf':  ['adviser', 'sector-food-farming'],
  'acco':  ['adviser', 'sector-defence'],
  'acia':  ['adviser', 'sector-health', 'sector-science'],
  'acjp':  ['adviser', 'sector-justice'],
  'acmd':  ['adviser', 'sector-health', 'sector-justice'],
  'acnfp': ['adviser', 'sector-food-farming', 'sector-health'],
  'acnra': ['adviser', 'sector-culture'],
  'acoba': ['adviser'],
  'acre':  ['adviser', 'sector-food-farming', 'sector-environment'],
  'afprb': ['review-body', 'sector-defence'],
  'arsac': ['regulator', 'sector-health', 'sector-science'],
  'asc':   ['adviser', 'sector-education'],
  'asc-animals': ['adviser', 'sector-science', 'sector-food-farming'],
  'bce':   ['adviser'],
  'bcni':  ['adviser'],
  'bcs':   ['adviser'],
  'bpc':   ['adviser', 'sector-food-farming'],
  'chm':   ['adviser', 'sector-health'],
  'cjc':   ['adviser', 'sector-justice'],
  'com':   ['regulator', 'sector-health'],
  'cprc':  ['adviser', 'sector-justice', 'sector-legal'],
  'crim-prc': ['adviser', 'sector-justice', 'sector-legal'],
  'ddrb':  ['review-body', 'sector-health'],
  'defra-sac': ['adviser', 'sector-environment', 'sector-food-farming'],
  'ethics-commission': ['adviser'],
  'fjc':   ['adviser', 'sector-justice', 'sector-legal'],
  'fprc':  ['review-body', 'sector-justice', 'sector-legal'],
  'holac': ['adviser'],
  'iaap':  ['adviser', 'sector-food-farming'],
  'iapdc': ['adviser', 'sector-justice'],
  'icai':  ['inspector', 'sector-international'],
  'ico-press': ['adviser', 'sector-media'],
  'iiac':  ['adviser', 'sector-welfare'],
  'imeg':  ['adviser', 'sector-defence', 'sector-welfare'],
  'irc':   ['adviser', 'sector-business'],
  'law-commission': ['adviser', 'sector-legal'],
  'lpc':   ['adviser', 'sector-business'],
  'mac':   ['adviser', 'sector-immigration'],
  'nhsprb': ['review-body', 'sector-health'],
  'nrac':  ['adviser', 'sector-nuclear'],
  'oprc':  ['adviser', 'sector-justice'],
  'pabew': ['review-body', 'sector-justice'],
  'prrb':  ['review-body', 'sector-justice'],
  'psprb': ['review-body', 'sector-justice'],
  'rcewa': ['adviser', 'sector-culture'],
  'rmac':  ['adviser', 'sector-finance'],
  'rpc':   ['adviser', 'sector-business'],
  'sentencing-council': ['adviser', 'sector-justice'],
  'smc':   ['adviser'],
  'ssac':  ['adviser', 'sector-welfare'],
  'ssrb':  ['review-body'],
  'ssrc':  ['adviser'],
  'steac': ['adviser', 'sector-science'],
  'strb':  ['review-body', 'sector-education'],
  'svap':  ['adviser'],
  'tab':   ['adviser', 'sector-justice'],
  'theatres-trust': ['adviser', 'sector-culture'],
  'tpc':   ['adviser', 'sector-justice'],
  'tvc':   ['adviser', 'sector-culture'],
  'vapc':  ['adviser', 'sector-veterans', 'sector-welfare'],
  'vpc':   ['adviser', 'sector-food-farming', 'sector-environment'],

  // Other bodies / tribunals / courts
  'bscc':  ['tribunal', 'sector-business'],
  'cac':   ['tribunal', 'sector-business'],
  'cat':   ['tribunal', 'sector-business'],
  'civil-service': [],
  'copyright-tribunal': ['tribunal', 'sector-culture', 'sector-business', 'sector-digital'],
  'direct-rail-services': ['sector-transport', 'sector-nuclear'],
  'iasc':  ['sector-immigration', 'sector-legal'],
  'icibi': ['inspector', 'sector-immigration'],
  'ipt':   ['tribunal', 'sector-security', 'sector-legal'],
  'nuclear-transport-solutions': ['sector-nuclear', 'sector-transport'],
  'pdat':  ['adviser', 'sector-justice'],
  'pensions-ombudsman': ['ombudsman', 'sector-welfare', 'sector-finance'],
  'ppfo':  ['sector-welfare', 'sector-finance'],
  'pvst':  ['adviser', 'sector-food-farming', 'sector-environment'],
  'traffic-commissioners': ['regulator', 'sector-transport'],
  'vte':   ['tribunal', 'sector-housing', 'sector-finance'],
  'bfs':   ['sector-immigration', 'sector-finance'],
  'ukvi':  ['sector-immigration'],
}

// ── Read and patch file ───────────────────────────────────────────────────────
const raw = readFileSync(filePath, 'utf8')
const eol = raw.includes('\r\n') ? '\r\n' : '\n'
const lines = raw.split(eol)

let patchCount = 0
const result = []
let i = 0

while (i < lines.length) {
  const line = lines[i]

  // Detect id: 'xxx' line
  const idMatch = line.match(/^\s+id: '([^']+)',/)
  if (idMatch) {
    const id = idMatch[1]
    const tags = tagMap[id]
    result.push(line)

    if (tags && tags.length > 0) {
      // Look ahead for childIds line (last field before closing },)
      // We'll insert tags: [...] after childIds
      let j = i + 1
      let childIdsLineIdx = -1
      let closingLineIdx = -1

      // Scan ahead up to 20 lines for childIds and closing brace
      for (let k = i + 1; k < Math.min(i + 25, lines.length); k++) {
        if (lines[k].includes('childIds:')) childIdsLineIdx = k
        if (lines[k].trim() === '},' || lines[k].trim() === '}') {
          closingLineIdx = k
          break
        }
      }

      if (childIdsLineIdx !== -1 && closingLineIdx !== -1) {
        // Check if tags already present
        let alreadyTagged = false
        for (let k = i + 1; k < closingLineIdx; k++) {
          if (lines[k].includes('tags:')) { alreadyTagged = true; break }
        }

        if (!alreadyTagged) {
          // Push all lines from i+1 up to and including childIds
          for (let k = i + 1; k <= childIdsLineIdx; k++) {
            result.push(lines[k])
          }
          // Insert tags line after childIds
          const indent = '    '
          const tagStr = tags.map(t => `'${t}'`).join(', ')
          result.push(`${indent}tags: [${tagStr}],`)
          patchCount++
          // Continue from after childIds
          i = childIdsLineIdx + 1
          continue
        }
      }
    }
    i++
    continue
  }

  result.push(line)
  i++
}

writeFileSync(filePath, result.join(eol), 'utf8')
console.log(`Tagged ${patchCount} elements`)
